#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
cp constant/polyMesh/orig.cellZones constant/polyMesh/cellZones
cp constant/polyMesh/orig.faces constant/polyMesh/faces
cp constant/polyMesh/orig.neighbour constant/polyMesh/neighbour
cp constant/polyMesh/orig.owner constant/polyMesh/owner
cp constant/polyMesh/orig.points constant/polyMesh/points
rm -f system/controlDict
rm -f system/fvSchemes
rm -f system/fvSolution
rm -f system/air/fvSchemes
rm -f system/air/fvSolution
rm -f system/rail/fvSchemes
rm -f system/rail/fvSolution

rm -rf 0 > /dev/null 2>&1
rm -f *.obj
rm -f constant/cellToRegion constant/polyMesh/boundary
rm -rf constant/cellToRegion constant/polyMesh/sets
rm -rf 0/air
rm -rf 0/rail
rm -f 0/cellToRegion
rm -rf constant/air/polyMesh
rm -rf constant/rail/polyMesh

# ----------------------------------------------------------------- end-of-file
