#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
cp constant/polyMesh/orig.cellZones constant/polyMesh/cellZones
cp constant/polyMesh/orig.faces constant/polyMesh/faces
cp constant/polyMesh/orig.neighbour constant/polyMesh/neighbour
cp constant/polyMesh/orig.owner constant/polyMesh/owner
cp constant/polyMesh/orig.points constant/polyMesh/points
rm -f *.obj
rm -f constant/cellToRegion constant/polyMesh/boundary
rm -f constant/cellToRegion constant/polyMesh/boundary_subsetMesh
rm -rf constant/cellToRegion constant/polyMesh/sets
rm -rf 0 > /dev/null 2>&1

# ----------------------------------------------------------------- end-of-file
