#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Set up for the (slightly) forced convection for flow initialization
cp system/air/changeDictionaryDict.forced system/air/changeDictionaryDict
cp system/controlDict.forced system/controlDict

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication topoSet
runApplication splitMeshRegions -cellZones -overwrite

# remove fluid fields from solid regions (important for post-processing)
for i in rail
do
   rm -f 0*/$i/{k,epsilon,U,p_rgh,p}
done


for i in air rail
do
   changeDictionary -region $i > log.changeDictionary.$i 2>&1
done


#-- Run on single processor
#runApplication `getApplication`

# Decompose
runApplication decomposePar -allRegions

# Run
runParallel `getApplication` 30

# Reconstruct
runApplication reconstructPar -allRegions

# Set up for the free convection
for x in log*;do mv $x forced_${x};done
rm -r processor*
rm -r postProcessing
cp system/air/changeDictionaryDict.free system/air/changeDictionaryDict
cp system/controlDict.free system/controlDict

for i in air rail
do
   changeDictionary -region $i > log.changeDictionary.$i 2>&1
done

# Decompose
runApplication decomposePar -allRegions

# Run
runParallel `getApplication` 30

# Reconstruct
runApplication reconstructPar -allRegions

echo
echo "creating files for paraview post-processing"
echo
paraFoam -touchAll

# ----------------------------------------------------------------- end-of-file
