#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r 0.orig 0 > /dev/null 2>&1
cp constant/polyMesh/boundary_full constant/polyMesh/boundary
runApplication topoSet
runApplication subsetMesh air -patch wall -overwrite
cp constant/polyMesh/boundary constant/polyMesh/boundary_subsetMesh
cp constant/polyMesh/boundary_air_only constant/polyMesh/boundary
#-- Run on single processor
#runApplication renumberMesh -overwrite
#runApplication `getApplication`

# Decompose
runApplication decomposePar 

runParallel renumberMesh 8 -overwrite
# Run
runParallel `getApplication` 8

# Reconstruct
runApplication reconstructPar -zeroTime
echo
echo "creating files for paraview post-processing"
echo
paraFoam -touchAll

# ----------------------------------------------------------------- end-of-file
