#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

if [ -z ${WM_NCOMPPROCS+x} ];
  then
    echo "WM_NCOMPPROCS is unset";
    exit 1;
  else
    echo "WM_NCOMPPROCS is set to '$WM_NCOMPPROCS'";
fi

cp system/controlDict.steadyState system/controlDict
cp system/fvSchemes.steadyState system/fvSchemes
cp system/fvSolution.steadyState system/fvSolution
cp system/air/fvSchemes.steadyState system/air/fvSchemes
cp system/air/fvSolution.steadyState system/air/fvSolution
cp system/rail/fvSchemes.steadyState system/rail/fvSchemes
cp system/rail/fvSolution.steadyState system/rail/fvSolution
cp constant/polyMesh/orig.cellZones constant/polyMesh/cellZones
cp constant/polyMesh/orig.faces constant/polyMesh/faces
cp constant/polyMesh/orig.neighbour constant/polyMesh/neighbour
cp constant/polyMesh/orig.owner constant/polyMesh/owner
cp constant/polyMesh/orig.points constant/polyMesh/points


cp -r 0.orig 0 > /dev/null 2>&1
cp constant/polyMesh/boundary_full constant/polyMesh/boundary

for i in system/decomposeParDict system/air/decomposeParDict system/rail/decomposeParDict
do
sed -i "s/numberOfSubdomains .*/numberOfSubdomains $WM_NCOMPPROCS;/" $i
done

runApplication topoSet
runApplication splitMeshRegions -cellZones -overwrite
# Convert tet mesh to polyhedral mesh
runApplication polyDualMesh -overwrite 45

# Map from potential case
runApplication mapFields ../OpenFOAM_Luxeon_potential -targetRegion air

# remove fluid fields from solid regions (important for post-processing)
for i in rail
do
   rm -f 0*/$i/{k,epsilon,U,p_rgh,p}
done

for i in air rail
do
   changeDictionary -region $i > log.changeDictionary.$i 2>&1
done

#-- Run on single processor
#runApplication `getApplication`

# Decompose
runApplication decomposePar -allRegions

runParallel renumberMesh $WM_NCOMPPROCS -overwrite -region air
mv log.renumberMesh air.log.renumberMesh
runParallel renumberMesh $WM_NCOMPPROCS -overwrite -region rail
mv log.renumberMesh rail.log.renumberMesh
# Run
runParallel `getApplication` $WM_NCOMPPROCS

# Reconstruct
runApplication reconstructPar -allRegions

echo
echo "creating files for paraview post-processing"
echo
paraFoam -touchAll

# ----------------------------------------------------------------- end-of-file
